steps:
- name: "gcr.io/cloud-builders/docker"
  args:
  - build
  - "--tag=gcr.io/stately-moon-405301/index"
  - "--file=./DockerFile.dockerfile"
  - .
- name: "gcr.io/cloud-builders/gcloud"
  args:
  - "run"
  - "deploy"
  - "--image=gcr.io/stately-moon-405301/index"
  - "--platform=managed"
  - "--region=us-central1"
  - "--allow-unauthenticated"
  - "--memory=1Gi"
  - "--set-env-vars=PYTHON_VERSION=3.10"
images:
- "gcr.io/stately-moon-405301/index"